BackEnd/src/main/java/com/example/backend/security/filter/FormLoginFilter.java
=> Feat : login input 데이터 명칭 변경

BackEnd/src/main/java/com/example/backend/controller/UserController.java, BackEnd/src/main/java/com/example/backend/dto/AuthPasswordDto.java
- 입력받은 비밀번호가 DB의 User 테이블의 비밀번호와 일치하는지 확인
=> Feat : 회원 / 가이드 비밀번호 수정 전 현재 비밀번호 확인 API

BackEnd/src/main/java/com/example/backend/exception/ErrorResponse.java, BackEnd/src/test/java/com/example/backend/BackEndApplicationTests.java, BackEnd/src/test/java/com/example/backend/controller/GuideSignUpApiTest.java
- 올바른 데이터를 입력받았을 때 성공 확인
- 올바르지 않은 데이터를 입력받았을 때 에러 확인
=> Feat : 가이드 회원가입 API Test Code 작성

BackEnd/src/test/java/com/example/backend/controller/AuthPasswordTest.java, BackEnd/src/test/java/com/example/backend/controller/LoginRequestDto.java
- 올바른 비밀번호를 입력했을 때 성공 확인
- 올바르지 않은 비밀번호를 입력했을 때 실패 확인
=> Feat : 비밀번호 확인 Test Code 작성

BackEnd/src/main/java/com/example/backend/controller/UserController.java, BackEnd/src/main/java/com/example/backend/dto/AuthPasswordDto.java, BackEnd/src/main/java/com/example/backend/service/UserService.java, BackEnd/src/test/java/com/example/backend/controller/AuthPasswordTest.java, BackEnd/src/test/java/com/example/backend/controller/LoginRequestDto.java
- 입력한 비밀번호로 해당 유저의 비밀번호를 변경
- DB의 비밀번호 변경 확인
- 변경된 비밀번호로 로그인 확인
=> Feat : 비밀번호 변경 API 작성

FrontEnd/src/routes/ChatRoom.tsx, FrontEnd/src/routes/LiveStreamView.jsx
=> Fix : 라이브 스트리밍 채팅 오류 수정

BackEnd/src/main/java/com/example/backend/dto/UserLoginDto.java, BackEnd/src/main/java/com/example/backend/security/FormLoginSuccessHandler.java
- 유저아이디, 닉네임, 이메일, 프로필이미지를 보내준다.
=> Feat : 로그인할 경우 Response Body 내용 변경

BackEnd/src/main/java/com/example/backend/security/SecurityConfig.java
=> Feat : Spring Security 설정 변경

FrontEnd/src/App.tsx, FrontEnd/src/components/LoginForm.tsx, FrontEnd/src/components/auth/Login.tsx, FrontEnd/src/routes/GuideSignup.jsx
=> Feat : 가이드 회원가입

FrontEnd/src/routes/ChatRoom.css, FrontEnd/src/routes/ChatRoom.tsx
=> Fix : 채팅 오류 수정

BackEnd/src/main/java/com/example/backend/util/awsS3/S3Uploader.java
- 파일 명을 UUID로 대체하여 동일한 이름의 파일이 저장될 때 오류 수정
=> Fix : 이미지 업로더 파일저장 후 URL 정보 변경 요청 #12

BackEnd/src/main/java/com/example/backend/service/TourService.java
- 투어 등록 시 이미지 첨부하지 않으면 투어가 등록 불가능 하던 부분 수정
=> Fix : 투어 등록 시 이미지 미첨부 가능

BackEnd/src/main/java/com/example/backend/controller/MateController.java, BackEnd/src/main/java/com/example/backend/dto/MateRegistDto.java, BackEnd/src/main/java/com/example/backend/service/MateService.java
- null 데이터에서 MateId를 보내주는 로직 추가
=> Feat : 프론트의 요구사항에 따라 메이트 등록 Response 값 변경

BackEnd/src/main/java/com/example/backend/dto/JoinerDto.java, BackEnd/src/main/java/com/example/backend/dto/TourDetailDto.java, BackEnd/src/main/java/com/example/backend/service/TourService.java
- 투어 데이터에 이미지 정보가 없는 경우에도 데이터 불러오게끔 수정
=> Fix : 투어 데이터에 이미지 없어도 불러오기#26

BackEnd/build.gradle, BackEnd/src/main/java/com/example/backend/controller/ChatController.java, BackEnd/src/main/java/com/example/backend/document/EventDoc.java, BackEnd/src/main/java/com/example/backend/document/EventRepository.java
- MongoDB와 SpringBoot를 연결하고 간단한 예제를 추가했습니다.
=> Feat : MongoDB Local connect 추가

BackEnd/src/main/java/com/example/backend/controller/MateController.java, BackEnd/src/main/java/com/example/backend/dto/MateInfoDetailDto.java, BackEnd/src/main/java/com/example/backend/service/MateService.java
- 메이트 상세에 Response 값으로 Tour Title 을 추가했습니다.
- 메이트 상세 API 와 메이트 리스트 API에 오타가 있어서 수정 했습니다.
=> Feat : 메이트 상세 Response 값 추가 및 오타 수정

BackEnd/src/main/java/com/example/backend/controller/TourController.java, BackEnd/src/main/java/com/example/backend/service/TourService.java
- 투어 아이디를 이용해 해당 투어 예약 현황을 찾음
- 사용자 아이디를 이용해 예약 현황에서 해당하는 사용자 정보를 삭제
=> Feat : 투어 예약 취소 Api 구현

BackEnd/src/main/java/com/example/backend/service/UserService.java
- 사용자 회원가입 시 등록되지 않은 카테고리를 추가하면 회원 가입 불가능하도록 수정
=> Fix : 사용자 회원가입 시 등록되지 않은 카테고리를 추가해도 회원가입 됨

BackEnd/src/main/java/com/example/backend/controller/UserInfoController.java, BackEnd/src/main/java/com/example/backend/dto/userinfo/UserFollowDto.java, BackEnd/src/main/java/com/example/backend/dto/userinfo/UserWishDto.java, BackEnd/src/main/java/com/example/backend/dto/userinfo/UserWishTourDto.java, BackEnd/src/main/java/com/example/backend/model/follower/FollowerRepository.java, BackEnd/src/main/java/com/example/backend/model/tour/TourRepository.java, BackEnd/src/main/java/com/example/backend/model/wish/WishRepository.java, BackEnd/src/main/java/com/example/backend/service/UserInfoService.java
- 유저가 팔로잉하고 있는 가이드의 목록을 출력할 수 있다
=> Feat : 사용자가 팔로잉하는 가이드 목록 API 작성

FrontEnd/src/components/pages/Auth/GeneralUpdate.tsx, FrontEnd/src/components/pages/Auth/Update.tsx, FrontEnd/src/components/pages/GuideProfile/GuideMyPage.css, FrontEnd/src/components/pages/GuideProfile/GuideMyPageMenu.tsx, FrontEnd/src/components/pages/GuideProfile/MyPageRightPanel.tsx, FrontEnd/src/navigations/App.tsx
=> Feat : 일반유저 사용자정보 수정 기능

FrontEnd/src/components/pages/Auth/GeneralUpdate.tsx
닉네임, 비밀번호, 비밀번호 확인, localStorage 자동갱신, 기존비밀번호와 새비밀번호 유효성검사, UI수정
=> Fix : 유저정보 수정페이지 완성

BackEnd/src/main/java/com/example/backend/controller/TourController.java, BackEnd/src/main/java/com/example/backend/service/TourService.java
- 리뷰를 등록할 때 주소에 tourId를 받지 않고 Body에서만 Request를 보낼 수 있도록 수정
=> Fix : 리뷰 등록 시 주소에 tourId를 받지 않도록 수정 #60

BackEnd/src/main/java/com/example/backend/dto/tour/ReviewRegistDto.java
- 리뷰 등록이 되지 않는 현상 발견
- tourId를 입력받지 못하는 것으로 판단하고 로직 수정
=> Fix : 리뷰 등록이 되지않는 현상 수정 #60

BackEnd/src/main/java/com/example/backend/service/TourService.java
- 끝난 뒤에 투어를 등록할 수 있어야하는데 반대로 넣음
=> Fix : 에러 관련 처리 로직 수정 #60

FrontEnd/src/components/pages/Auth/GeneralUpdate.tsx
유저정보 수정페이지 nickname 입력창 반환로직 직관성 개선
=> Fix : 유저정보 수정페이지 직관성 개선

FrontEnd/src/components/pages/Auth/GeneralUpdate.tsx, FrontEnd/src/components/pages/Auth/GuideUpdate.tsx
=> Feat : 가이드정보 수정페이지

FrontEnd/src/components/pages/Auth/GeneralUpdate.tsx, FrontEnd/src/components/pages/Auth/GuideUpdate.tsx, FrontEnd/src/components/pages/Auth/Update.tsx
=> Feat : 유저, 가이드 정보 수정페이지 컴포넌트연결

FrontEnd/src/components/blocks/Header.tsx, FrontEnd/src/components/pages/Auth/GeneralUpdate.tsx, FrontEnd/src/components/pages/Auth/GuideUpdate.tsx, FrontEnd/src/components/pages/Auth/Update.tsx
- 로그아웃시 localStorage에서 제거되는 항목에 userType 추가
=> Fix : logout Remove 추가

FrontEnd/src/components/blocks/Header.tsx, FrontEnd/src/components/pages/Auth/GeneralUpdate.tsx, FrontEnd/src/components/pages/Auth/GuideUpdate.tsx, FrontEnd/src/components/pages/Auth/Update.tsx
=> Feat : 가이드 자기소개(공지사항) 기능 추가

FrontEnd/src/components/blocks/FollowingCard.jsx, FrontEnd/src/components/pages/UserProfile/UserFollowingBoard.jsx
=> Feat : 유저 팔로잉 가이드 페이지 완성

BackEnd/src/main/generated/com/example/backend/model/course/QCourse.java, BackEnd/src/main/java/com/example/backend/dto/userinfo/GuideInfoForUserFollowDto.java, BackEnd/src/main/java/com/example/backend/dto/userinfo/GuideInfoForUserTourDto.java, BackEnd/src/main/java/com/example/backend/dto/userinfo/ReviewInfoForGuideReviewDto.java, BackEnd/src/main/java/com/example/backend/dto/userinfo/TourInfoForUserTourDto.java, BackEnd/src/main/java/com/example/backend/dto/userinfo/UserInfoForGuideReviewsDto.java, BackEnd/src/main/java/com/example/backend/model/review/ReviewRepository.java, BackEnd/src/main/java/com/example/backend/service/UserInfoService.java
- Front-End의 요청에 따라 imageUrl과 전체 리뷰 평균 평점을 전달할 수 있도록 함
- 생성자를 활용해 일부 코드를 간결화했음
=> Feat : 사용자 팔로잉 가이드 리스트 추가 정보 전달

FrontEnd/src/components/blocks/FollowingCard.jsx, FrontEnd/src/components/pages/GuideProfile/GuideDetail.css, FrontEnd/src/components/pages/GuideProfile/GuideMyPage.css, FrontEnd/src/components/pages/UserProfile/UserMain.jsx, FrontEnd/src/components/pages/UserProfile/UserNavbar.jsx
=> Fix : 이미지 전역에서 왼쪽정렬 되던 현상 수정

FrontEnd/src/components/blocks/FollowerCard.jsx, FrontEnd/src/components/pages/GuideProfile/GuideFollower.jsx, FrontEnd/src/components/pages/GuideProfile/GuideMain.jsx
=> Feat : 가이드프로필 팔로워페이지 구현(api미적용)

FrontEnd/src/components/blocks/FollowerCard.jsx, FrontEnd/src/components/pages/GuideProfile/GuideFollower.jsx, FrontEnd/src/components/pages/GuideProfile/GuideMain.jsx
=> Feat : 팔로워카드 컴포넌트 구현(api미적용)

FrontEnd/src/components/blocks/TourCard.jsx, FrontEnd/src/components/pages/UserProfile/UserCanceledBoard.jsx, FrontEnd/src/components/pages/UserProfile/UserEndedBoard.jsx, FrontEnd/src/components/pages/UserProfile/UserScheduledBoard.jsx, FrontEnd/src/components/pages/UserProfile/UserTourBoard.jsx, FrontEnd/src/components/pages/UserProfile/UserTourNavbar.jsx, FrontEnd/src/index.css
=> Feat : 마이페이지 완성

FrontEnd/src/components/blocks/FollowingCard.jsx, FrontEnd/src/components/blocks/WishCard.jsx
=> Fix : 로딩중 문구 수정

BackEnd/src/main/java/com/example/backend/controller/TourController.java, BackEnd/src/main/java/com/example/backend/controller/UserInfoController.java, BackEnd/src/main/java/com/example/backend/dto/userinfo/GuideFollowerDto.java, BackEnd/src/main/java/com/example/backend/security/SecurityConfig.java, BackEnd/src/main/java/com/example/backend/service/UserInfoService.java
- 가이드를 팔로우 한 팔로워들의 목록 불러오기
- 팔로워들의 정보는 아이디, 닉네임, 프로필 이미지만 출력
=> Feat : 가이드 팔로워 목록 Api 구현

FrontEnd/src/components/blocks/FollowerCard.jsx, FrontEnd/src/components/pages/GuideProfile/GuideFollower.jsx, FrontEnd/src/components/pages/GuideProfile/GuideMain.jsx
=> Feat : 가이드 팔로워페이지, 카드컴포넌트 API 적용

FrontEnd/src/components/pages/Auth/GeneralUpdate.tsx, FrontEnd/src/components/pages/Auth/GuideUpdate.tsx, FrontEnd/src/navigations/App.tsx
- 기존 비밀번호와 새 비밀번호 일치할 경우 비밀번호 변경불가
=> Fix : 기존 비밀번호와 새 비밀번호 일치할 경우 비밀번호 변경불가

FrontEnd/src/components/blocks/Header.tsx, FrontEnd/src/components/blocks/TourListCard.jsx, FrontEnd/src/components/pages/Tour/TourBoard.jsx, FrontEnd/src/navigations/App.tsx
=> Fix : 일부 이미지 버그 임시 조치

FrontEnd/src/components/blocks/TourListCard.jsx
=> Fix : 투어 이미지 에러 수정

FrontEnd/src/components/blocks/Searchbar.jsx, FrontEnd/src/components/blocks/TourListCard.jsx, FrontEnd/src/components/pages/Tour/TourBoard.jsx
=> Feat : 검색 기능 일부 구현

FrontEnd/src/components/blocks/FollowBtn.jsx, FrontEnd/src/components/pages/Auth/GeneralUpdate.tsx, FrontEnd/src/components/pages/Auth/GuideUpdate.tsx, FrontEnd/src/components/pages/GuideProfile/GuideMini.jsx, FrontEnd/src/components/pages/GuideProfile/GuideMyPage.jsx
=> Fix : 수정페이지/마이페이지 연결

FrontEnd/index.html, FrontEnd/src/components/pages/Auth/GeneralLogin.tsx, FrontEnd/src/components/pages/Auth/GeneralUpdate.tsx, FrontEnd/src/components/pages/Auth/GuideUpdate.tsx, FrontEnd/src/index.css
- Fix : 로그인 성공할 경우 백그라운드 페이지 접근 유지
=> Fix : 로그인 성공할 경우 백그라운드 페이지 접근 유지
